Update activation.yml

diff --git a/.github/workflows/activation.yml b/.github/workflows/activation.yml
--- a/.github/workflows/activation.yml
+++ b/.github/workflows/activation.yml
@@ -1,36 +1,52 @@
-name: Unity Test
+name: Acquire activation file
 
 on:
-  push:
-    branches:
-      - main
+  workflow_dispatch:
 
 jobs:
-  build:
+  activation:
+    name: Request manual activation file 🔑
     runs-on: ubuntu-latest
-
     steps:
+      # Checkout repository (required to test local actions)
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      # Request manual activation file
+      - name: Request manual activation file
+        id: getManualLicenseFile
+        continue-on-error: true
+        uses: ./
+
+      - name: Check for failure
+        run: |
+          if [ "${{ steps.getManualLicenseFile.outcome }}" != "failure"  ]; then
+            echo "Expected failure, got ${{ steps.getManualLicenseFile.outcome }}"
+            exit 1
+          fi
+      # Request manual activation file
+      - name: Unity - Request Activation File
+        id: requestActivationFile
+        uses: game-ci/unity-request-activation-file@v2.0-alpha-1
+      - name: Upload activation file
+        uses: actions/upload-artifact@v2
+        with:
+          name: ${{ steps.requestActivationFile.outputs.filePath }}
+          path: ${{ steps.requestActivationFile.outputs.filePath }}
+          retention-days: 3
       - name: Checkout Repository
         uses: actions/checkout@v2
 
       - name: Set up Unity
         uses: actions/cache@v1.1.0
         with:
-          path: ~/.nuget/packages
+          unity-version: 2022.3.7f1  # 사용할 Unity 버전
 
       - name: Install NUnit
         run: |
           dotnet new tool-manifest
           dotnet tool install nunit.console --tool-path ./.nuget
           export PATH="$PATH:$(pwd)/.nuget"
-
-      - name: Activate Unity
-        uses: kuler90/activate-unity@v1
-        with:
-          unity-username: ${{ secrets.UNITY_USERNAME }}
-          unity-password: ${{ secrets.UNITY_PASSWORD }}
-          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
-
       - name: Run Unit Tests
         run: |
-          nunit3-console Library/ScriptAssemblies/Tests.dll
+          nunit3-console Library\ScriptAssemblies\Tests.dll  # 유닛 테스트 실행할 DLL 경로 지정
