Update activation.yml

diff --git a/.github/workflows/activation.yml b/.github/workflows/activation.yml
--- a/.github/workflows/activation.yml
+++ b/.github/workflows/activation.yml
@@ -1,67 +1,50 @@
-name: Actions
+name: Acquire activation file
 
-on: [push, pull_request]
+on:
+  workflow_dispatch:
 
 jobs:
-  test:
-    name: Test my project 🧪
+  activation:
+    name: Request manual activation file 🔑
     runs-on: ubuntu-latest
     steps:
-      # Checkout
+      # Checkout repository (required to test local actions)
       - name: Checkout repository
         uses: actions/checkout@v4
-        with:
-          lfs: true
 
-      # Cache
-      - uses: actions/cache@v3
-        with:
-          path: Library
-          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
-          restore-keys: |
-            Library-
+      # Request manual activation file
+      - name: Request manual activation file
+        id: getManualLicenseFile
+        continue-on-error: true
+        uses: ./
 
-      # Test
-      - name: Run tests
-        uses: game-ci/unity-test-runner@v4
-        env:
-          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
-          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
-          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+      - name: Check for failure
+        run: |
+          if [ "${{ steps.getManualLicenseFile.outcome }}" != "failure"  ]; then
+            echo "Expected failure, got ${{ steps.getManualLicenseFile.outcome }}"
+            exit 1
+          fi
+      # Request manual activation file
+      
+      - name: Unity - Request Activation File
+        id: requestActivationFile
+        uses: game-ci/unity-request-activation-file@v2.0-alpha-1
+      - name: Upload activation file
+        uses: actions/upload-artifact@v2
         with:
-          githubToken: ${{ secrets.GITHUB_TOKEN }}
+          name: ${{ steps.requestActivationFile.outputs.filePath }}
+          path: ${{ steps.requestActivationFile.outputs.filePath }}
+          retention-days: 3
 
-  build:
-    name: Build my project ✨
-    runs-on: ubuntu-latest
-    steps:
-      # Checkout
-      - name: Checkout repository
-        uses: actions/checkout@v4
+      - name: Set up Unity
+        uses: actions/cache@v1.1.0
         with:
-          lfs: true
-
-      # Cache
-      - uses: actions/cache@v3
-        with:
-          path: Library
-          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
-          restore-keys: |
-            Library-
-
-      # Build
-      - name: Build project
-        uses: game-ci/unity-builder@v4
-        env:
-          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
-          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
-          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
-        with:
-          targetPlatform: StandaloneWindows64
-          allowDirtyBuild: false
-
-      # Output
-      - uses: actions/upload-artifact@v3
-        with:
-          name: Build
-          path: build
+          unity-version: 2022.3.7f1  # 사용할 Unity 버전
+          
+      - name: Install NUnit and add to PATH
+        run: |
+          echo "$(pwd)/.nuget" >> $GITHUB_PATH
+          
+      - name: Run Unit Tests
+        run: |
+          nunit3-console Library/ScriptAssemblies/Tests.dll  # 유닛 테스트 실행할 DLL 경로 지정
